name: Release
on:
  push:
    tags: 
      - "*"
env:
  GOPROXY: https://proxy.golang.org
  GO111MODULE: on
  HOME_OVERRIDE: ./homedir
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [1.16.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          stable: true
          go-version: ${{ matrix.version }}
      - name: Add Ubuntu Packages
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install libgl1-mesa-dev xorg-dev gcc-multilib 
      - name: Windows Release 
        if: ${{ matrix.os == 'windows-latest' }}
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release -f release-config/windows.yml --rm-dist
      - name: Linux Release 
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release -f release-config/linux.yml --rm-dist
      - name: Test MacOS Release 
        if: ${{ matrix.os == 'macos-latest' }}
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release -f release-config/mac.yml --rm-dist

